name: diginews_app
description: "A new Flutter project for Enterprise Smart Dashboard DigiNews."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons untuk iOS style icons
  cupertino_icons: ^1.0.6

  # 1. Architecture & Navigation [cite: 24]
  go_router: ^14.0.0
  get_it: ^7.6.0

  # 2. Networking & State Management [cite: 28, 29, 30]
  dio: ^5.4.0
  flutter_bloc: ^8.1.3

  # 3. Database & Animation [cite: 36, 37]
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter standar Flutter
  flutter_lints: ^3.0.0

  # Testing & Generator [cite: 45]
  mocktail: ^1.0.4
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Mendaftarkan aset untuk animasi Lottie Easter Egg lo nanti [cite: 36, 39]
  assets:
    - assets/